import jsPDF from 'jspdf';
import { Bill } from './BillingService';

const MARGIN = 14;
const PAGE_WIDTH = 210; // A4 mm
const PAGE_HEIGHT = 297;
const CONTENT_RIGHT = PAGE_WIDTH - MARGIN;

function money(n?: number): string {
  return `Rs. ${(n ?? 0).toFixed(2)}`;
}

function formatDate(raw?: string): string {
  if (!raw) return '—';
  const d = new Date(raw);
  if (isNaN(d.getTime())) return raw;
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

/** Draws one bill's receipt starting at the current page position of `doc`. */
function drawBill(doc: jsPDF, bill: Bill, hospitalName?: string) {
  let y = 20;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(6, 182, 212); // cyan-500, matches app branding
  doc.text('Hospitonet', MARGIN, y);
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text('Payment Receipt', CONTENT_RIGHT, y, { align: 'right' });
  y += 8;

  doc.setDrawColor(220);
  doc.line(MARGIN, y, CONTENT_RIGHT, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(30);
  doc.text(`Bill No: ${bill.billNumber ?? bill.id}`, MARGIN, y);
  doc.text(`Date: ${formatDate(bill.billDate)}`, CONTENT_RIGHT, y, { align: 'right' });
  y += 6;
  if (hospitalName) {
    doc.text(`Hospital: ${hospitalName}`, MARGIN, y);
  }
  doc.text(`Status: ${bill.status ?? '—'}`, CONTENT_RIGHT, y, { align: 'right' });
  y += 10;

  doc.setFont('helvetica', 'bold');
  doc.text('Patient', MARGIN, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.text(`${bill.patientName ?? '—'}`, MARGIN, y);
  const demo = [bill.patientAge ? `${bill.patientAge}y` : null, bill.patientGender].filter(Boolean).join(' · ');
  if (demo) doc.text(demo, CONTENT_RIGHT, y, { align: 'right' });
  y += 8;

  if (bill.billCategory === 'Appointment' && (bill.doctor || bill.department)) {
    doc.setFont('helvetica', 'bold');
    doc.text('Consultation', MARGIN, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.text([bill.doctor, bill.department].filter(Boolean).join(' · '), MARGIN, y);
    y += 8;
  }

  // Items table
  y += 2;
  doc.setFillColor(245, 247, 250);
  doc.rect(MARGIN, y, CONTENT_RIGHT - MARGIN, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Item', MARGIN + 2, y + 5.5);
  doc.text('Qty', 130, y + 5.5, { align: 'right' });
  doc.text('Price', 155, y + 5.5, { align: 'right' });
  doc.text('Amount', CONTENT_RIGHT - 2, y + 5.5, { align: 'right' });
  y += 8;

  doc.setFont('helvetica', 'normal');
  for (const item of bill.items ?? []) {
    if (y > PAGE_HEIGHT - 40) { doc.addPage(); y = 20; }
    const qty = item.quantity ?? 1;
    const price = item.price ?? 0;
    doc.text(item.name ?? item.code ?? 'Item', MARGIN + 2, y + 5);
    doc.text(String(qty), 130, y + 5, { align: 'right' });
    doc.text(money(price), 155, y + 5, { align: 'right' });
    doc.text(money(price * qty), CONTENT_RIGHT - 2, y + 5, { align: 'right' });
    y += 7;
  }

  y += 4;
  doc.setDrawColor(220);
  doc.line(MARGIN, y, CONTENT_RIGHT, y);
  y += 8;

  const totalsRow = (label: string, value: string, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(bold ? 11 : 9.5);
    doc.text(label, 150, y, { align: 'right' });
    doc.text(value, CONTENT_RIGHT, y, { align: 'right' });
    y += bold ? 7 : 6;
  };
  totalsRow('Subtotal', money(bill.subtotal));
  totalsRow('Tax', money(bill.tax));
  totalsRow('Discount', `- ${money(bill.discount)}`);
  doc.setTextColor(6, 182, 212);
  totalsRow('Total', money(bill.total), true);
  doc.setTextColor(30);

  y += 6;
  if (bill.paymentMode) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`Paid via ${bill.paymentMode}`, MARGIN, y);
    y += 5;
  }

  doc.setFontSize(8);
  doc.setTextColor(160);
  doc.text('Generated by Hospitonet — this is a system-generated receipt.', MARGIN, PAGE_HEIGHT - 12);
}

export function downloadBill(bill: Bill, hospitalName?: string): void {
  const doc = new jsPDF();
  drawBill(doc, bill, hospitalName);
  doc.save(`${bill.billNumber ?? bill.id}.pdf`);
}

export function downloadAllBills(bills: Bill[], hospitalNameFor: (bill: Bill) => string | undefined): void {
  if (bills.length === 0) return;
  const doc = new jsPDF();
  bills.forEach((bill, i) => {
    if (i > 0) doc.addPage();
    drawBill(doc, bill, hospitalNameFor(bill));
  });
  doc.save(`hospitonet-bills-${new Date().toISOString().split('T')[0]}.pdf`);
}
